version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build